# docker needs these permissions
sudo: required

servies:
  - docker

# series of set up before run tests
before_install:
  # by default the build returns id of the image created, so we tag
  - docker build -t michael.kang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michael.kang/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-727449613345"
  bucket_path: "docker-react"
  on: 
    branch: master