version: '3'
services:
  web-ui:
    build: 
      context: '.'
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # this current folder, to the app folder in the container
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # override default command
    command: ["npm", "run", "test"]
